from .buffer_errors import *
from .config_loader import get_config_section, load_global_config

__all__ = [
    "get_config_section",
    "load_global_config",
    # Metadata
    "BufferCategory",
    "BufferSeverity",
    "BufferErrorCode",
    "BufferErrorContext",
    "BufferRecoveryHint",
    # Base
    "BufferError",
    "BufferWarning",
    # Config
    "BufferConfigError",
    "ConfigFileNotFoundError",
    "ConfigPathError",
    "ConfigParseError",
    "InvalidConfigSectionError",
    "MissingConfigValueError",
    "ConfigValueError",
    "ConfigReloadError",
    # Transition validation
    "TransitionValidationError",
    "TransitionTypeError",
    "TransitionLengthError",
    "TransitionRewardError",
    "TransitionDoneError",
    "TransitionNoneStateError",
    "TransitionSchemaError",
    "TransitionCoercionError",
    "TransitionBatchValidationError",
    # Capacity / state / storage
    "BufferCapacityError",
    "BufferFullError",
    "BufferEmptyError",
    "InsufficientSamplesError",
    "InvalidBatchSizeError",
    "IndexOutOfBoundsError",
    "BufferStateError",
    "BufferClosedError",
    "BufferLockTimeoutError",
    "BufferMutationError",
    # Replay / sampling
    "ReplayBufferError",
    "DistributedReplayBufferError",
    "ReservoirBufferError",
    "SamplingError",
    "InvalidSamplingStrategyError",
    "PrioritySamplingError",
    "PriorityUpdateError",
    "PriorityMassError",
    "AgentDistributionError",
    "StaleExperienceError",
    # Persistence
    "BufferPersistenceError",
    "BufferSaveError",
    "BufferLoadError",
    "BufferSerializationError",
    # Network buffer
    "NetworkBufferError",
    "NetworkMessageError",
    "MessageExpiredError",
    "MessageNotFoundError",
    "DuplicateMessageError",
    "FairnessKeyError",
    "FairnessSchedulingError",
    "DropStrategyError",
    "BackpressureError",
    "BackpressureRejectedError",
    "InflightLimitError",
    "TTLValidationError",
    "AckError",
    "NackError",
    # N-step
    "NStepBufferError",
    "NStepConfigError",
    "NStepWindowError",
    "NStepComputationError",
    "NStepTerminalStateError",
    # Segment tree
    "SegmentTreeError",
    "SegmentTreeCapacityError",
    "SegmentTreeIndexError",
    "SegmentTreeRangeError",
    "SegmentTreePrefixSumError",
    "SegmentTreeMassError",
    "SegmentTreeOperationError",
    # Eviction
    "EvictionError",
    "EvictionContextError",
    "EvictionPolicyError",
    "UnsupportedEvictionPolicyError",
    "EvictionSelectionError",
    # Sequence replay
    "SequenceReplayError",
    "InvalidSequenceLengthError",
    "SequenceReplayAssemblyError",
    "SequencePaddingError",
    # Telemetry / fairness
    "TelemetryError",
    "TelemetryMetricError",
    "MetricValueError",
    "MetricSnapshotError",
    "FairnessMetricError",
    "FairnessViolationError",
    "TelemetryDisabledWarning",
    "FairnessViolationWarning",
    # Bulk operations
    "BufferOperationError",
    "BufferPartialFailureError",
    # Helpers
    "build_error_context",
    "ensure",
    "ensure_positive_int",
    "ensure_non_empty",
    "ensure_index_in_bounds",
    "coerce_buffer_error",
    "summarize_errors",
]
