# config.yaml

agent:
  input_size: 10
  output_size: 2
  hidden_sizes: [16, 32, 64, 128]
  learning_rate: 0.001
  epochs: 5
  batch_size: 16

evaluator:
  threshold: 70.0

training:
  num_samples: 500
