agent_meta:
  default_version: "1.0.0"
  required_fields: ["name", "class_name", "module_path"]
  validation_rules:
    max_name_length: 50
    allowed_modules: ["src.agents.core", "src.agents.specialized"]

metrics:
  history_size: 100
  max_adaptation_rate: 0.2
  pid_params:
    Kp: 0.15
    Ki: 0.05
    Kd: 0.02
  safety_bounds:
    medical: 0.5
    default: 0.4
  error_config:
    fairness_target: 1.0
    performance_target: 0.0
    bias_target: 0.0
