# ==============================================
# Unified Hyperparameter Tuning Configuration
# Supports both Grid Search and Bayesian Search
# ==============================================

model:
  name: SLAI-Agent
  version: v1.4.1

run:
  id_prefix: "run"
  output_dir: "logs/"
  plots_dir: "plots/"

agent:
  type: dqn
  state_dim: 4
  action_dim: 2
  hidden_size: 128
  learning_rate: 0.001
  gamma: 0.99
  epsilon: 1.0
  epsilon_decay: 0.995
  epsilon_min: 0.01
  buffer_size: 10000
  batch_size: 64
  target_update_frequency: 100

agent:
  type: maml
  state_size: 52
  action_size: 3
  hidden_size: 64
  meta_lr: 0.001
  inner_lr: 0.01
  gamma: 0.99

agent:
  type: rsi
  state_size: 52
  action_size: 3
  shared_memory: null  # Or pass a mock/dummy instance in agent_factory

agent:
  type: eval

training:
  num_samples: 500

evaluator:
  threshold: 0.9

# ==========================
# Hyperparameters Definition
# ==========================

hyperparameters:
  - name: learning_rate
    type: float
    min: 0.0001
    max: 0.1
    prior: log-uniform
    steps: 5

  - name: num_layers
    type: int
    min: 1
    max: 10
    step: 1

  - name: batch_size
    type: int
    min: 16
    max: 256
    step: 16

  - name: optimizer
    type: categorical
    choices: [adam, sgd, rmsprop]

  - name: activation
    type: categorical
    choices: [relu, tanh, sigmoid]

  - name: dropout_rate
    type: float
    min: 0.0
    max: 0.5
    steps: 6

  - name: gamma
    type: float
    min: 0.8
    max: 0.999
    steps: 5


# ==========================
# Tuning Strategy Settings
# ==========================

tuning:
  strategy: bayesian         # options: bayesian, grid
  n_calls: 20                # used for Bayesian
  n_random_starts: 5         # used for Bayesian

configs:
  bayesian_config: "hyperparam_tuning/example_bayesian_config.json"
  grid_config: "hyperparam_tuning/example_grid_config.json"

# ==========================
# Thresholds and Alignment
# ==========================

alignment_thresholds:
  bias_threshold: 0.1
  reward_threshold: 70.0
  statistical_parity: 0.1
  equal_opportunity: 0.1
  predictive_parity: 0.1
  individual_fairness: 0.1

rollback:
  enabled: true
  backup_dir: "models/backups/"

retrain:
  enabled: true
  trigger_on_violation: true

logging:
  log_file: "logs/app.log"
  level: INFO
  rotate: true
  max_size_mb: 50
  backup_count: 10

# ==========================
# Security Settings
# ==========================

security:
  encrypt_models: true
  enable_threat_detection: true
  adversarial_training: false
  backup_on_threat: true

# ==========================
# Compliance & Ethics
# ==========================
compliance:
  regulations:
    - GDPR
    - CCPA
  enable_audit: true
  anonymize_data: true
  consent_management: true

# ==========================
# Monitoring & Drift
# ==========================
monitoring:
  enable_monitoring: true
  drift_detection:
    enabled: true
    threshold: 0.05
  performance_monitoring:
    interval_seconds: 300  # 5 minutes
  alerting:
    enable_alerts: true
    alert_thresholds:
      performance_drop: 0.1
      bias_increase: 0.05

paths:
  data_source: "datasets/sample_dataset.csv"
