# ==============================================
# Unified Hyperparameter Tuning Configuration
# Supports both Grid Search and Bayesian Search
# ==============================================

model:
  name: SLAI-Agent
  version: v1.4.1

run:
  id_prefix: "run"
  output_dir: "logs/"
  plots_dir: "plots/"

training:
  num_samples: 500

# ==========================
# Hyperparameters Definition
# ==========================

hyperparameters:
  - name: learning_rate
    type: float
    min: 0.0001
    max: 0.1
    prior: log-uniform
    steps: 5

  - name: num_layers
    type: int
    min: 1
    max: 10
    step: 1

  - name: batch_size
    type: int
    min: 16
    max: 256
    step: 16

  - name: optimizer
    type: categorical
    choices: [adam, sgd, rmsprop]

  - name: activation
    type: categorical
    choices: [relu, tanh, sigmoid]

  - name: dropout_rate
    type: float
    min: 0.0
    max: 0.5
    steps: 6

  - name: gamma
    type: float
    min: 0.8
    max: 0.999
    steps: 5

  - name: TaskA
    type: int
    min: 0
    max: 2

  - name: TaskB
    type: int
    min: 0
    max: 3

# ==========================
# Tuning Strategy Settings
# ==========================

tuning:
  strategy: bayesian         # options: bayesian, grid
  n_calls: 20                # used for Bayesian
  n_random_starts: 5         # used for Bayesian

configs:
  bayesian_config: "hyperparam_tuning/example_bayesian_config.json"
  grid_config: "hyperparam_tuning/example_grid_config.json"
