safety_margins:
  resource_buffers:
    gpu: 0.15           # 15% of available GPUs must remain unallocated
    ram: 0.2            # 20% of total RAM must remain free
    specialized_hardware: ["emergency_gpu"]  # Reserved hardware units
  temporal:
    min_task_duration: 30  # Minimum allowed task duration in seconds
    max_concurrent: 5      # Max simultaneous tasks per agent
    time_buffer: 120       # Minimum gap between dependent tasks (seconds)

service_discovery:
  mode: "static"  # Options: static|consul|k8s
  static_nodes: [] # OR add "node1", "node2", "gpu-node1"
  consul_url: "http://localhost:8500"
  k8s_api: "https://kubernetes.default.svc"
  k8s_token: ""
  node_port: 9100  # Port for node metrics API

decomposition:
  min_chunk_size: 100      # Minimum data elements per horizontal split
  max_parallel_chunks: 8   # Maximum concurrent data chunks
  min_ram_per_chunk: 4     # GB RAM guaranteed per data chunk
  vertical_stages:
    ABSTRACT:  # Match TaskType.ABSTRACT
      - name: "default_stage"
        gpu: 0
        ram: 8
    processing_pipeline:
      - name: "preprocessing"
        gpu: 0
        ram: 8
      - name: "core_processing"
        gpu: 1
        ram: 16
        specialized_hw: ["tensor_core"]
      - name: "postprocessing"
        gpu: 0
        ram: 4
  stage_time_buffer: 60    # Buffer between stage deadlines (seconds)

cluster_monitoring:
  node_query_timeout: 2    # Seconds to wait for node response
  update_interval: 5       # Seconds between resource updates
  discovery_poll_interval: 300  # Seconds between node discovery scans
  load_thresholds:
    cpu: 0.85              # CPU usage alert threshold
    memory: 0.9            # Memory usage alert threshold
    temperature: 70        # GPU temperature threshold (°C)

task_scheduler:
  risk_threshold: 0.7
  retry_policy:
    max_retries: 3
    max_attempts: 3
    backoff_factor: 1.5
    delay: 10
  base_duration_per_requirement: 5.0  # Time per capability requirement
  efficiency_attribute: "efficiency"  # Key in agent's details for efficiency

decision_tree_heuristic:
  max_depth: 8
  min_samples_split: 15
  min_impurity_decrease: 0.01
  ccp_alpha: 0.02
  class_weight: "balanced"
  feature_config:
    use_temporal_features: true
    use_priority_weighting: true
    use_method_complexity: false
  validation:
    test_size: 0.25
    max_training_samples: 10000

gradient_boosting_heuristic:
  n_estimators: 200
  learning_rate: 0.05
  max_depth: 5
  subsample: 0.8
  min_samples_split: 10
  early_stopping_rounds: 20
  validation_fraction: 0.2
  class_weight: "balanced"
  feature_config:
    use_priority: true
    use_resource_check: true
    recent_success_window: 10

planning_memory:
  max_checkpoints: 20                  # Maximum stored planning states
  history_window: 1000                 # Execution history items to retain
  retention_days: 7                    # Auto-delete checkpoints older than this
  compression: false                   # Enable checkpoint compression
  auto_save_interval: 300              # Seconds between auto-saves (0=disabled)

planning_metrics:
  enable_timing: true          # Whether to require timing data
  default_task_cost: 1.0       # Fallback cost for tasks without cost attribute
  default_task_duration: 0.5   # Fallback duration (seconds) when timing data missing
  use_length_fallback: true    # Use plan length * duration when no timing data
  metrics_weights:
    success: 0.5               # Weight for success rate in efficiency score
    cost: 0.3                  # Weight for cost efficiency
    time: 0.2                  # Weight for time efficiency

planning_monitor:
  metrics_window: 100          # Number of plans to retain for trend analysis
  anomaly_thresholds:
    success_rate: 0.65         # Minimum acceptable success rate
    cpu_peak: 85.0             # Max CPU% before alert
    memory_peak: 4096          # Max MB before alert
  check_intervals:
    plan_execution: 5          # Check metrics every N plans
    resource_scan: 300         # Full system scan every N seconds
  method_analysis_depth: 10    # Track top N most used methods

planning_types:
  default_constraints: []
  type_checks: enabled
  validation_level: strict

learning_retraining_scheduler:
  risk_threshold: 0.4
  base_duration_per_requirement: 300  # 5 minutes per requirement
  efficiency_attribute: "efficiency"
  max_concurrent_training: 3
