src_vocab_size: 50000
tgt_vocab_size: 50000
bpe_model_path: "data/bpe_200d_50k_model.json"
bpe_vocab_path: "data/bpe_200d_50k_vocab.json"

base_transformer:
  d_model: 512
  nhead: 8
  num_encoder_layers: 6
  num_decoder_layers: 6
  dim_feedforward: 2048
  dropout: 0.1
  activation: "relu"
  layer_norm_eps: 0.00001
  batch_first: True
  clip_grad: 1.0
  max_len: 5000
  lr: 0.0001
  betas: [0.9, 0,98]
  eps: 0.000000001
  weight_decay: 0.0001

inference:
  max_len: 50
  sos_token: 1
  eos_token: 2
  temperature: 1.0

forward:
  src_mask: None
  tgt_mask: None
  memory_mask: None
  src_key_padding_mask: None
  tgt_key_padding_mask: None
  memory_key_padding_mask: None

base_tokenizer:
  pad_token: "[PAD]"
  unk_token: "[UNK]"
  bos_token: "[BOS]"
  eos_token: "[EOS]"
  mask_token: "[MASK]"
  special_tokens: None

encode:
  max_length: None
  padding: "max_length"
  truncation: True
  add_special_tokens: True
  return_tensors: None
  src_mask: None
  src_key_padding_mask: None


decode:
  skip_special_tokens: True
  clean_up_tokenization_spaces: True
  tgt_mask: None
  memory_mask: None
  tgt_key_padding_mask: None
  memory_key_padding_mask: None

lm_store:
  enable_memory_tracking: true
  default_category: "performance"
  max_history_size: 1000

lazy_agent:
  max_init_attempts: 3
  enable_init_logging: true
  timeout_seconds: 30
