maml:
  state_size: 4
  action_size: 2
  hidden_size: 64
  meta_lr: 0.001
  inner_lr: 0.01
  gamma: 0.99
  envs:
    - CartPole-v1
    - MountainCar-v0

safe_ai_agent:
  risk_threshold: 0.2
  enable_rlhf: true
  alignment_config: "alignment_config.yaml"

adaptation_agent:
  concept_drift_threshold: 0.15
  performance_decay_threshold: 0.25
  ewc_lambda: 0.4
  replay_buffer_size: 1000

eval_agent:
  validation_protocol:
    static_analysis:
      enable: true
      max_critical: 0
    behavioral_testing:
      sample_size:
        nominal: 100
        edge_cases: 20
        adversarial: 10

planning_agent:
  plan_depth: 3
  heuristic: "entropy_minimization"

perception_agent:
  model_type: "cnn"
  input_dim: 64
  output_dim: 10
  learning_rate: 0.001

reasoning_agent:
  logic_backend: "prolog"
  max_depth: 4

language_agent:
  tokenizer: "bert-base-uncased"
  use_context: true

execution_agent:
  retry_attempts: 3
  fallback_policy: "safe_mode"

knowledge_agent:
  ontology_file: "ontology.owl"
  inference_method: "backward_chaining"

learning_agent:
  episodes: 500
  batch_size: 64
  epsilon_decay: 0.995
