monitor:
  fairness_metrics:
    - statistical_parity
    - equal_opportunity
  drift_threshold: 0.15
  audit_frequency: 1000

ethics:
  safety_constraints:
    physical_harm: ["Prevent injury"]
  fairness_constraints:
    distribution: ["Ensure equity"]

memory:
  replay_buffer_size: 10000
  retention_period: 365

corrections:
  levels:
    - threshold: 0.1
      action: log_warning
    - threshold: 0.3
      action: human_intervention
