memory:
  replay_buffer_size: 10000
  causal_window: 1000
  drift_threshold: 0.25
  retention_period: 365

ethics:
  constraints:
    - "Do not generate discriminatory content"
    - "Uphold user dignity and agency"
    - "Avoid promoting misinformation"
    - "Respect user privacy and autonomy"

constitutional_rules:
  privacy: []
  safety: []
  ethics: []
  - "Prioritize investor safety over returns"
  - "Avoid high-risk leverage in bear markets"
risk_thresholds:
  safety: 0.01
  security: 0.001
  privacy: 0.05
  max_var: 0.05
  max_drawdown: 0.2

audit_level: 2

monitor:
  fairness_metrics:
    - demographic_parity
    - equal_opportunity
    - predictive_equality
  ethical_rules:
    privacy:
      - "No sharing of personally identifiable information (PII)"
    fairness:
      - "Avoid bias towards protected attributes like gender or race"
    transparency:
      - "Explain decisions if confidence is low"
  drift_threshold: 0.15
  audit_frequency: 1000
  adaptive_weights:
    fairness: 0.4
    ethics: 0.3
    safety: 0.3

value_model:
  embedding_dim: 128
  similarity_threshold: 0.85
  use_contextual_embedding: true
  weights:
    helpfulness: 0.6
    harmlessness: 0.2
    honesty: 0.2

corrections:
  levels:
    - threshold: 0.1
      action: log_warning
    - threshold: 0.2
      action: adjust_reward
    - threshold: 0.3
      action: human_intervention
    - threshold: 0.5
      action: agent_suspension
  learning_rate: 0.01
  momentum: 0.9
