required_fields: ["name", "contact_email"]
central_hub:
  latitude: 12.516
  longitude: -70.035

main: {}

foodie_memory:
  max_session_history: 5
  max_menu_items: 100

registrator:
  allowed_cuisine_types: [
    "Local", "International", "Fusion", "Seafood",
    "Vegan", "Dessert", "Vegetarian", "Local Snack",
    "Sushi", "Caribbean", "Italian", "Asian",
    "American", "Mexican", "Other"
    ]
  max_menu_items: 50
  restaurant_dir: "foodie/data/restaurant/"
  seller_dir: "foodie/data/seller/"

foodie_users:
  max_addresses: 5
  max_payment_methods: 3
  user_dir: "foodie/data/user"
  allowed_dietary_restrictions: [
    "vegetarian", "vegan", "gluten-free", "dairy-free", "nut-free",
    "halal", "kosher", "pescatarian", "low-carb", "low-sodium",
    "low-fat", "sugar-free", "egg-free", "soy-free", "shellfish-free",
    "paleo", "keto", "whole30", "raw", "organic", "heart-healthy"
  ]

foodie_orders:
  batch_dir: "foodie/data/"
  order_statuses: [
    "pending", "payment_pending", "processing", "confirmed",
    "preparing", "ready_for_pickup", "picked_up", "out_for_delivery",
    "delayed", "delivered", "delivery_failed", "refunded",
    "cancelled", "rejected"
  ]
  business_order_fields: [
    "company_name", "company_address", "contact_name",
    "email", "employee_count", "frequency", "details", 
    "cuisine_preferences", "arrival_time", "registration_number"
  ]

foodie_card:
  max_title_length: 50
  max_description_length: 120
  allowed_card_types: ['featured', 'restaurant', 'indie']
  default_image: 'foodie/static/img/logo.png'
  rating_icon: '<i class="fa-solid fa-star"></i>'

foodie_map:
  avoid_tolls: True
  api_key: "${MAP_API_KEY}"
  base_url: "https://api.mapservice.com/v1/"
  traffic_endpoint: "/traffic"
  weather_endpoint: "/weather"
  route_endpoint: "/directions"

foodie_security:
  password_rules:
    min_length: 10
    require_uppercase: True
    require_lowercase: True
    require_digit: True
    require_special: True
  session_timeout_minutes: 30
  max_login_attempts: 5
  allowed_roles: []
  role_permissions: {}
  session_db_path: "foodie/data/sessions.json"
  reset_token_db_path: "foodie/data/password_reset_tokens.json"
  rate_limit_db_path: "foodie/data/rate_limits.json"
  rate_limit_window: 3600

foodie_support:
  categories: ["order_issue", "payment_issue", "delivery_issue", "account_issue", "technical_issue", "other"]
  priorities: ["low", "medium", "high", "urgent"]
  max_open_tickets: 5
  data_dir: 'foodie/data/support/'

web_socket:
  status: "initialized"
  url: "http://127.0.0.1:5000"
  timeout: 5