inference:
  default_chain_length: 5         # Max steps in chain-of-thought reasoning
  neuro_symbolic_weight: 0.4      # Weight for neural vs symbolic reasoning (0.0-1.0)
  max_hypotheses: 100             # Cap on number of hypotheses retained
  exploration_rate: 0.1           # Probability to trigger rule discovery
  llm_fallback:
    enable: true
    temperature: 0.3
    max_tokens: 100

rules:
  enable_learning: true           # Enable adaptive rule discovery
  min_support: 0.3                # Minimum support threshold for discovered rules
  min_confidence: 0.7             # Minimum confidence threshold for valid rules
  auto_weight_adjustment: true    # Allow reinforcement learning on rule weights
  max_circular_depth: 3           # Limit for detecting rule circularity

validation:
  enable: true
  min_soundness_score: 0.7
  contradiction_threshold: 0.25   # Confidence conflict threshold between contradictory facts

nlp:
  sentence_transformer: "slailm-v2"
  tokenizer: "slailm-tokenizer"
  enable_pragmatic_heuristics: true
  use_semantic_frames: true

storage:
  knowledge_db: "src/agents/knowledge/knowledge_db.json"
  rule_backup: "src/agents/knowledge/discovered_rules.json"
  lexicon_path: "src/agents/language/sentiment_lexicon.json"
